[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
  0%|          | 0/38 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home01/hpc72a03/.conda/envs/shard/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 319, in _poll_FSDP
    self.run_schedule(self.schedules, init=False)
  File "/scratch/hpc72a03/shardscheduler/torch_scheduler.py", line 835, in run_schedule
    print(param.shape)
UnboundLocalError: local variable 'param' referenced before assignment
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 149791 ON gpu10 CANCELLED AT 2022-11-12T23:14:44 ***
  3%|â–Ž         | 1/38 [00:00<00:36,  1.02it/s]slurmstepd: error: *** STEP 149791.0 ON gpu10 CANCELLED AT 2022-11-12T23:14:44 ***
